apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  labels:
    app: webserver
spec:
  replicas: {{.Values.replica_pod}}
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
      - name: webserver
        image: ajmezav/webserver:latest
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: webserver
  labels:
    app: webserver
spec:
  type: ClusterIP
  selector:
    app: webserver
  ports:
    - protocol: TCP
      port: 80 #puerto en el que servicio va escuchar
      targetPort: 80 # A que puerto dentro del pod voy a consumir
      
---
apiVersion: v1
kind: Service
metadata:
  name: hola
  labels:
    app: hola
spec:
  type: ClusterIP
  selector:
    app: webserver
  ports:
    - protocol: TCP
      port: 80 #puerto en el que servicio va escuchar
      targetPort: 80 # A que puerto dentro del pod voy a consumir

